site_name: "Lamini Docs"
site_url: "https://lamini-ai.github.io"

theme:
  name: material
  custom_dir: overrides
  features:
    - content.code.copy
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.footer
    - navigation.tabs
    - navigation.tabs.sticky
  logo: assets/logo.png
  favicon: assets/favicon.png
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  icon:
    admonition:
      note: octicons/tag-16

extra_css:
  - stylesheets/extra.css
  - stylesheets/oad.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details

extra:
  analytics:
    provider: custom
    HUBSPOT_TRACKING_URL: !ENV HUBSPOT_TRACKING_URL
    UNIFY_TRACKING_KEY: !ENV UNIFY_TRACKING_KEY
    UNIFY_TRACKING_URL: !ENV UNIFY_TRACKING_URL
    RB2B_TRACKING_KEY: !ENV RB2B_TRACKING_KEY
    GOOGLE_ANALYTICS_KEY: !ENV GOOGLE_ANALYTICS_KEY

# Page tree
nav:
  - Documentation:
      - Get Started:
          - Introduction: index.md
          - Quick Start: quick_start.md
          - FAQ: faq.md
      - Memory Experiments:
          - Quick Start: memory_experiments/index.md
          - Best Practices: memory_experiments/best_practices.md
          - Generators: memory_experiments/generators.md
          - Validators: memory_experiments/validators.md
          - Pipelines: memory_experiments/pipelines.md
          - Prompt Formatting: memory_experiments/prompt_formatting.md
          - Evaluation: memory_experiments/evaluation.md
          - Text to SQL: memory_experiments/txt2sql.md
          - Factual QA: memory_experiments/factual_qa.md
      - Memory Tuning:
          - Quick Start: tuning/memory_tuning.md
          - Hyperparameters: tuning/hyperparameters.md
          - Large Data Files: tuning/large_data_files.md
          - Evaluation UI: tuning/evaluation.md
      - Inference:
          - Quick Start: inference/quick_start.md
          - OpenAI API: inference/infv2.md
          - Prompt Templates: inference/prompt_templates.md
          - JSON Output: inference/json_output.md
          - Batching: inference/batching.md
          - Streaming: inference/streaming.md
          - Performance: inference/performance.md
      - Platform:
          - API Authentication: authenticate.md
          - Supported Models: models.md
      - Self-Hosted Lamini:
          - Kubernetes Install: self_managed/kubernetes_install.md
          - AWS EKS Setup: self_managed/aws_eks_setup.md
          - GCP GKE Setup: self_managed/gcp_gke_setup.md
          - OIDC User Auth: self_managed/OIDC.md
          - Model Management: self_managed/model_management.md
      - License: LICENSE.md
  - Python SDK:
      - lamini: lamini_python_class/lamini.md
  - REST API: api.md

plugins:
  - redirects:
      redirect_maps:
        "enterprise_install.md": "self_managed/kubernetes_install.md"
        "get_started/authenticate.md": "authenticate.md"
        "get_started/install.md": "authenticate.md"
        # "inference/quick_start.md": "quick_start.md"
        "inference/quick_tour.md": "quick_start.md"
        "inference/prompt_tuning.md": "inference/prompt_templates.md"
        "overview.md": "index.md"
        "rest_api/completions.md": "api.md"
        "rest_api/embed.md": "api.md"
        "rest_api/train.md": "api.md"
        "rest_api/train_jobs.md": "api.md"
        "rest_api/train_job_status.md": "api.md"
        "rest_api/train_job_cancel.md": "api.md"
        "self_managed/docker_install.md": "self_managed/kubernetes_install.md"
        "training/memory_tuning.md": "tuning/memory_tuning.md"
        "training/quick_start.md": "quick_start.md"
        "training/quick_tour.md": "quick_start.md"
        "tuning/quick_start.md": "quick_start.md"
  - search
  - swagger-ui-tag
