site_name: "Lamini Docs"
site_url: "https://lamini-ai.github.io"

theme:
  name: material
  features:
    - content.code.copy
    - navigation.instant
    - navigation.tracking
    - navigation.expand
  logo: assets/logo.png
  favicon: assets/favicon.png
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  icon:
    admonition:
      note: octicons/tag-16

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details

extra:
  analytics:
    provider: google
    property: G-6ZQD4KPE0G

# Page tree
nav:
  - Introduction:
      - Overview: overview.md
      - About: about.md
      - Authenticate: authenticate.md
      - Enterprise Install: enterprise_install.md
      - FAQ: faq.md
  - Inference:
      - Quick Start: inference/quick_start.md
      - Prompt Tuning: inference/prompt_tuning.md
      - JSON Output: inference/json_output.md
      - Batching: inference/batching.md
      - Retrieval Augmented Generation (RAG) 🔗: "https://github.com/lamini-ai/lamini-sdk/blob/main/04_rag_tuning/README.md"
  - Tuning:
      - Quick Start: tuning/quick_start.md
      - Memory Tuning: tuning/memory_tuning.md
      - Hyperparameters: tuning/hyperparameters.md
      - Large Data Files: tuning/large_data_files.md
      - Evaluation: tuning/evaluation.md
      - Dashboard: tuning/dashboard.md
  - Playground: inference/playground.md
  - Applications:
       - Pipeline: applications/pipeline.md
       - Classifier: applications/classifier.md
  - SDK 🔗: "https://github.com/lamini-ai/lamini-sdk"
  - Python API reference:
      - lamini: lamini_python_class/lamini.md
      - upload_data: lamini_python_class/upload_data.md
  - REST API reference:
      - completions: rest_api/completions.md
      - embed: rest_api/embed.md
      - train: rest_api/train.md
      - train_jobs: rest_api/train_jobs.md
      - train_job_status: rest_api/train_job_status.md
      - train_job_cancel: rest_api/train_job_cancel.md
      - eval_results: rest_api/eval_results.md

plugins:
  - redirects:
      redirect_maps:
        'get_started/install.md': 'authenticate.md'
        'get_started/authenticate.md': 'authenticate.md'
        'index.md': 'overview.md'
