name: Code test
on:
  push:
    branches:
      - main
  workflow_call:
    secrets:
      production_key:
        required: true

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: pip3 install lamini
      - run: |
          PRODUCTION_KEY=${{ secrets.production_key }} python3 -m unittest discover -v -s docs/ -p "*.py"
