name: Code test
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: pip3 install lamini
      - run: |
          mkdir -p ~/.powerml
          echo "production:" > ~/.powerml/configure_llama.yaml
          echo "  key: ${{ secrets.production_token }}" >> ~/.powerml/configure_llama.yaml
          python3 -m unittest discover -v -s "sample_code.py"
